name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Publish to Hex.pm
        uses: wesleimp/action-publish-hex@v1
